drop table products if exists;

CREATE TABLE products (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_type varchar(255),
  product_code varchar(255),
  rank integer not null,
  unit_price decimal(19,2),
  introduced date,
  last_modified timestamp,
  primary key (id)
);