drop table products if exists;
drop table customers if exists;

CREATE TABLE products (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_type varchar(255),
  product_code varchar(255),
  rank integer not null,
  unit_price decimal(19,2),
  introduced date,
  last_modified timestamp,
  primary key (id)
);

CREATE TABLE customers (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255),
  version INTEGER not null default 0,
  primary key (id)
);